{% set name = "tl2cgen" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dmlc/tl2cgen/archive/{{ version }}.tar.gz
  sha256: e7e29be473b9af6c6a606d537b2f7349767a465eaa86d5ee511b5b540b54322a

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake >=3.16
    - ninja
    - gtest
    - fmt
    - rapidjson
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip >=22.1
    - hatchling >=1.12.1
    - treelite >=3.4,<4
  run:
    - python
    - numpy
    - scipy
    - packaging
    - treelite >=3.4,<4

test:
  requires:
    - packaging
  imports:
    - tl2cgen

about:
  home: https://github.com/dmlc/tl2cgen
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: TL2cgen (TreeLite 2 C GENerator)

  description: |
    TL2cgen is a model compiler for decision tree models.
    You can convert any decision tree models (random forests,
    gradient boosting models) into C code and distribute it
    as a native binary. TL2cgen seamlessly integrates with Treelite.
    Any tree models that are supported by Treelite can be
    translated using TL2cgen.
  doc_url: https://tl2cgen.readthedocs.io/
  dev_url: https://github.com/dmlc/tl2cgen

extra:
  recipe-maintainers:
    - hcho3
